[package]
name = "guessing_game"
version = "0.1.0"
edition = "2023"
authors = 'Eric Hao <hhao99@gmail.com>'

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
